### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by LadanTazik** [data301-2020-winter2/course-project-solo_105#3]
# High priority (must-fix)

- [ ]  The EDA task (Task 4) is different from the Analysis task (Task 5). The EDA is “exploratory” in nature and is done at a superficial level to get counts of columns, limits, ranges, understand the data distribution, and a cursory look at the relationships between the columns. Think of it as a ‘quick and dirty' analysis of your data in preparation for a more thorough. Move those analyses to task 5 and add EDA.

**Comment by Marium-E-Jannat** [comment]
Hello @LadanTazik! It would be great and really helpful if you could manage time to check now. I have fixed the issue but not sure if it is that what you have mentioned.

**Comment by LadanTazik** [comment]
Well done! 
Please move the research questions to the top of task 5 to give your report a nice start about why you have those plots in your analysis! You'll walk the reader through your report, and it makes it more organized.
No need to fix it. It's a suggestion.

**Comment by Marium-E-Jannat** [comment]
Thanks @LadanTazik for your feedback and support. I am adjusting all the feedbacks in my milestone3.ipynb. Thanks a lot :)
